# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 09:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxrisk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BzEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 30, 9, 12, 48, 467541, tzinfo=utc))),
                ('deleted_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 30, 9, 12, 48, 467657, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDEntity',
            fields=[
                ('bzentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxrisk.BzEntity')),
                ('registry_id', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 30, 9, 12, 48, 469082, tzinfo=utc), null=True)),
            ],
            bases=('taxrisk.bzentity',),
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('bzentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxrisk.BzEntity')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('taxrisk.bzentity',),
        ),
        migrations.AddField(
            model_name='bzentity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bzentity_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bzentity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bzentity_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('identity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxrisk.IDEntity')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateTimeField(default=datetime.datetime(2017, 12, 30, 9, 12, 48, 469836, tzinfo=utc))),
            ],
            bases=('taxrisk.identity',),
        ),
        migrations.AddField(
            model_name='identity',
            name='registered_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxrisk.Registry'),
        ),
    ]
