# Generated by Django 2.0 on 2017-12-30 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxrisk', '0002_auto_20171230_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzentity',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 10, 2, 4, 146477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bzentity',
            name='deleted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 30, 10, 2, 4, 146538, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 30, 10, 2, 4, 147567, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 10, 2, 4, 148086, tzinfo=utc)),
        ),
    ]
