# Generated by Django 2.0 on 2017-12-30 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxrisk', '0003_auto_20171230_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzentity',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 10, 32, 50, 710956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bzentity',
            name='deleted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 30, 10, 32, 50, 711016, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 30, 10, 32, 50, 712054, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 10, 32, 50, 712556, tzinfo=utc)),
        ),
    ]
